version: '3'
services:
  reids:
    # https://github.com/docker-library/redis/blob/e964e2975dabf8169edcbf89a72d4163191de02e/4.0/Dockerfile
    image: redis:4.0
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379" 
